#!/usr/bin/python3

import datetime
import sys

print("Valid for 2023 ONLY without updating source!!")
first_payday = datetime.datetime(2023, 1, 6)
i = first_payday
remaining_paydays = 0
comparator = datetime.datetime.today()
if len(sys.argv) > 1:
    comparator = datetime.datetime.strptime(sys.argv[1], '%Y-%m-%d')
#print(comparator)
while i <= datetime.datetime(2023, 12, 31):
    if i > comparator:
        remaining_paydays += 1
    i += datetime.timedelta(14)

print(remaining_paydays)
